### PR TITLE
Add favicon to plugin portal

### PR DESCRIPTION
**Pull request by matthiasblaesing**
Icon integration follows the sample set by the main apache netbeans
website. The icons and manifest files are copied from the source code
of that website.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Thanks for the quick review!

**Comment by matthiasblaesing** [comment]
@jkovalsky do you know if we have a workflow how such changes are put into production?

**Comment by jkovalsky** [comment]
[https://cwiki.apache.org/confluence/display/NETBEANS/NetBeans+Plugin+Portal+Administration#NetBeansPluginPortalAdministration-HowdoesredeploymentofPluginPortalsourceswork?](https://cwiki.apache.org/confluence/display/NETBEANS/NetBeans+Plugin+Portal+Administration#NetBeansPluginPortalAdministration-HowdoesredeploymentofPluginPortalsourceswork?)

**Comment by matthiasblaesing** [comment]
@jkovalsky thx - I realize that a "let me google that for you" reply would have been appropriate :-)

**Pull request merged**
