### PR TITLE
[NETBEANS-5039] Remove duplicate '/' from the download URL

### PR DESCRIPTION
**Pull request by junichi11**
[NETBEANS-5039](https://issues.apache.org/jira/browse/NETBEANS-5039)

### CODE REVIEW

**Review by jkovalsky — APPROVED** [review]
I am not sure when $this->_downloadPath does NOT contain the slash character but this fix accounts for both possibilities.
Thanks Junichi! Approved.

**Comment by jkovalsky** [comment]
[](url)

**Comment by johanvos** [comment]
Looks safe and good.

**Review by matthiasblaesing — APPROVED** [review]
Change looks sane to me. Thank you for the fix and sorry, that I broke it in the first place. Not intentionally :-)

**Comment by junichi11** [comment]
Thank you for your reviews.

@matthiasblaesing Don't worry. We appreciate your improvements for PP :)

**Pull request merged**
