### PR TITLE
Implement a proxy chooser for the Update Centers

### PR DESCRIPTION
**Pull request by matthiasblaesing**
This is an experimental implementation of a proxy chooser for the netbeans update center.

For further information, please see the `README.md` added with this PR.

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Definitely a step in the right direction! Only had a quick browse, so may not be reading correctly, but if this is relying on the updates.xml from downloads.a.o and archive.a.o it's not going to handle all requirements. Needs to be a file we can edit.

**Comment by matthiasblaesing** [comment]
Thank you for having a look. It is a bit more sophisticated:

- First the main download server is checked if an `update.xml.gz` for the target version is present. The file is not fetched, but only a HEAD request issued to check if the file is present. The check happens here: https://github.com/apache/netbeans-tools/blob/8d8fa220d5482427ca381fdcf1724f09b5b04007/proxy-chooser/updates.php#L268. This information is used as an indicator to use the mirror network. The updates.xml.gz used as base is read from the local file.
- If the file is not not on the download server, the archive is checked (again a HEAD request): https://github.com/apache/netbeans-tools/blob/8d8fa220d5482427ca381fdcf1724f09b5b04007/proxy-chooser/updates.php#L269. If the file is present again the local file is used to serve the updates.xml.gz.
- If a CI build (again check via HEAD request) is found, the updates.xml.gz from the build is used. I admit, this is a hack, but IMHO a hack on the same level as the redirects in .htaccess. I thought about parsing the .htaccess in the version folder, but that seemed similar unstable as directly checking the target systems.

The `updates.xml.gz` is cached locally to reduce strain on the target servers and the VM.

What am I missing?

**Comment by neilcsmith-net** [comment]
> The updates.xml.gz used as base is read from the local file.

Thanks, yes wasn't sure exactly where the contents for that are taken from though?  eg. this line is possibly concerning 

https://github.com/apache/netbeans-tools/blob/8d8fa220d5482427ca381fdcf1724f09b5b04007/proxy-chooser/updates.php#L120

Doesn't that assume all links are relative?  But the updates.xml from the release isn't what's actually served to users.  Check the updates file for 12.0 for instance - that currently has a number of absolute URLs, and directly to closer.lua.  That is currently how updates are shipped.  We need to be able to handle that usage, and I wasn't sure if this code can at the moment?  Also, ideallly the updates should use the same mirror as selected for the rest.

When archiving we also add notifications to the XML about new releases.  And there are potentially other cases for editing that file that don't assume relative links.

Key thing is that whatever solution we have here has to handle the fact that there is no file on dist.a.o that will, or can, have the required contents.

One minor point - the crunch point here "closer.lua is hit many times and can cause blocks because this is detected as abuse of the the download system" I've not seen - the more likely rate limiting you'll hit is netbeans.a.o to netbeans-vm1.a.o.  You can see this using the Ant platform scripts to download the clusters in a build.  The proxy chooser should hopefully fix that issue too though.  And it's a use case we should check against too.

**Comment by matthiasblaesing** [comment]
For the "relative" assumption - you are right, that was not correct and needs to be corrected. I had to take a closer look at the 12.0 updates.xml. After your request and explanation it is kind of obvious.

For the "hit closer.lua remark": I think that point came up in earlier discussions - I never saw it in reality, but then I'm just a developer building the nightly myself, so I hit the autoupdate scenario not very often.

I'll give it another spin.

**Comment by neilcsmith-net** [comment]
> For the "hit closer.lua remark": I think that point came up in earlier discussions - I never saw it in reality, but then I'm just a developer building the nightly myself, so I hit the autoupdate scenario not very often.

Possibly, although I've commented on the upstream (n.a.o -> n-vm.a.o) redirect a few times - most users should hit rate limit rarely unless they're reinstalling whole clusters.  I do test that sometimes - it's flaky!  The platform build scripts include this - https://github.com/apache/netbeans/blob/master/nb/updatecenters/extras/nbproject/platform.xml#L32  It's an Ant task that downloads all of the modules required as part of a build through the update centre.  It's the other reason people might make a large hit on the UCs.  Just worth keeping in mind if it's a use case we intend to keep supporting.

You may notice autoupdate with the dev build more now - the UC was changed a couple of weeks ago.

**Comment by matthiasblaesing** [comment]
The update should address the concerns:

- the `url` attribute for `notification` and `content_description` was not touched
- absolute URLs are now not again prefixed with the `baseHref`
- references to `closer.lua` are resolved against the mirror, that holds the `update.xml.gz`. This means, that all artifacts have to have the same state (Mirrored/Archived/CI) - I think that is a sane assumption.

**Comment by neilcsmith-net** [comment]
Looks like it should. :+1: Something to look at testing, probably against 12.0 UC.

Longer term we should find an alternative to adding the closer URLs into the catalog manually, perhaps also parsing multiple catalogs into one here too, but this should hopefully solve some of the immediate issues.

**Pull request merged**
