### PR TITLE
Check in of Javadoc publishing code from NetBeans VM.

### PR DESCRIPTION
**Pull request by neilcsmith-net**
Check in of Javadoc publishing code from NetBeans VM.

@ebarboni @vieiro couldn't find this code checked in anywhere?  Thought it would be useful to have in a repo somewhere.

### CODE REVIEW

**Comment by ebarboni** [comment]
thanks to taking care of that @neilcsmith-net  we MP on that a while ago with @vieiro but we forget to follow up

**Comment by neilcsmith-net** [comment]
@ebarboni shall I merge this? Got waylaid by other things, and just noticed it here while creating another PR.

**Comment by ebarboni** [comment]
I think so would be nice to have the vm in sync with this .

**Comment by ebarboni** [comment]
we do that on the vm puppet script now we may close this one

**Comment by neilcsmith-net** [comment]
Good with me.  As we found out, I hadn't updated the PR after making changes anyway! :roll_eyes:

**Pull request closed without merging**
