### PR TITLE
Add improvements and methods to convert the localisation bundles

### PR DESCRIPTION
**Pull request by borisheithecker**
This PR fixes one typo, adds support for old Sun licenses and adds method needed to convert the localisation bundles. Property bundles are either fixed and copied from a source directory to a target folder. If a license header replacement is not possible, the bundle files are re-assembled line by line.

### CODE REVIEW

**Comment by geertjanw** [comment]
Thanks!

**Comment by geertjanw** [comment]
But why Sun licenses?

**Comment by borisheithecker** [comment]
Because they can still be found in the language bundles.

**Comment by geertjanw** [comment]
Can they be replaced with the Apache license?

**Comment by borisheithecker** [comment]
The PR adds another pattern to recognize and replace them (just like the Oracle licenses). 
Do we need to double-check the legal part?

**Comment by geertjanw** [comment]
So long as all licenses become Apache (instead of Oracle or Sun) anything is good.

**Pull request merged**
