### PR TITLE
Prepare for a release of NBPackage

### PR DESCRIPTION
**Pull request by neilcsmith-net**
Some steps to prepare to do a release of NBPackage.

Move from AppAssembler to Assembly plugin, with binary and source archives.
Update POM to use netbeans-parent and enable RAT checks.
Add missing version query.

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
@ebarboni welcome your thoughts particularly on use of netbeans-parent and whether there's anything missing in the POM to look towards doing an actual release (as standalone binary, not to central)?

**Comment by ebarboni** [comment]
I would create a git repo for that :D (change log, dependabot, easy to release auto tag and so on) . It could live on central too.

I suggest adding a javadoc plugin section otherwise it break the build (maybe using compiler 3.10.1 instead of too old)
+    <pluginManagement>
+    <plugins>
+      <plugin>
+        <groupId>org.apache.maven.plugins</groupId>
+        <artifactId>maven-javadoc-plugin</artifactId>
+        <version>3.4.1</version>
+        <configuration>
+          <release>11</release>
+        </configuration>
+      </plugin>
+    </plugins>
+    </pluginManagement> 

I've tested mvn clean install -Papache-release as it flags more than standard mvn clean install.

**Comment by neilcsmith-net** [comment]
Thanks @ebarboni will take a look using `-Papache-release`.  Short term plan would be just on dist.a.o.  Central would be nice later, as possibility to put a simple plugin wrapper around it for RCP?

Agree, might be better in a separate repo - was suggested to start it in this one, but dependabot, change log, and testing would be better separate.  I'll wait until this and RPM changes in before considering that.

**Comment by neilcsmith-net** [comment]
@ebarboni addressed the Javadoc issue and fixed a few errors, and exported the API package so it shows up in the docs! Thanks for the pointers.

**Pull request merged**
